/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.exoplatform.services.wsrp1.bind;

import java.util.logging.Logger;

import org.exoplatform.services.wsrp1.intf.AccessDenied;
import org.exoplatform.services.wsrp1.intf.InconsistentParameters;
import org.exoplatform.services.wsrp1.intf.InvalidCookie;
import org.exoplatform.services.wsrp1.intf.InvalidHandle;
import org.exoplatform.services.wsrp1.intf.InvalidRegistration;
import org.exoplatform.services.wsrp1.intf.InvalidSession;
import org.exoplatform.services.wsrp1.intf.InvalidUserCategory;
import org.exoplatform.services.wsrp1.intf.MissingParameters;
import org.exoplatform.services.wsrp1.intf.OperationFailed;
import org.exoplatform.services.wsrp1.intf.PortletStateChangeRequired;
import org.exoplatform.services.wsrp1.intf.UnsupportedLocale;
import org.exoplatform.services.wsrp1.intf.UnsupportedMimeType;
import org.exoplatform.services.wsrp1.intf.UnsupportedMode;
import org.exoplatform.services.wsrp1.intf.UnsupportedWindowState;
import org.exoplatform.services.wsrp1.intf.WSRPV1MarkupPortType;
import org.exoplatform.services.wsrp2.producer.MarkupOperationsInterface;
import org.exoplatform.services.wsrp2.type.BlockingInteractionResponse;
import org.exoplatform.services.wsrp2.type.GetMarkup;
import org.exoplatform.services.wsrp2.type.InitCookie;
import org.exoplatform.services.wsrp2.type.RegistrationContext;
import org.exoplatform.services.wsrp2.type.ReleaseSessions;
import org.exoplatform.services.wsrp2.type.UserContext;

/**
 * This class was generated by Apache CXF 2.1.2 Sun Dec 21 18:13:35 EET 2008
 * Generated source version: 2.1.2
 */

@javax.jws.WebService(name = "WSRPV1MarkupPortType", serviceName = "WSRPService", portName = "WSRPMarkupService", targetNamespace = "urn:oasis:names:tc:wsrp:v1:wsdl", wsdlLocation = "file:/home/alexey/java/eXoProjects/portlet-container/branches/2.1/component/plugins/wsrp2/wsdl1/wsrp_service.wsdl", endpointInterface = "org.exoplatform.services.wsrp1.intf.WSRPV1MarkupPortType")
public class WSRPV1MarkupPortTypeImpl implements WSRPV1MarkupPortType {

  private MarkupOperationsInterface markupOperationsInterface;
  
  private static final Logger LOG = Logger.getLogger(WSRPV1MarkupPortTypeImpl.class.getName());

  public WSRPV1MarkupPortTypeImpl(MarkupOperationsInterface markupOperationsInterface) {
    this.markupOperationsInterface = markupOperationsInterface;
  }
  
  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1MarkupPortType#releaseSessions(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)java.util.List<java.lang.String>  sessionIDs )*
   */
  public java.util.List<org.exoplatform.services.wsrp1.type.Extension> releaseSessions(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                                                                                       java.util.List<java.lang.String> sessionIDs) throws InvalidRegistration,
                                                                                                                                   MissingParameters,
                                                                                                                                   AccessDenied,
                                                                                                                                   OperationFailed {
    LOG.info("Executing operation releaseSessions");
    System.out.println(registrationContext);
    System.out.println(sessionIDs);
    try {
      RegistrationContext registrationContext = new RegistrationContext();
      
      UserContext userContext = new UserContext();
      ReleaseSessions releaseSessions = markupOperationsInterface.releaseSessions(registrationContext, sessionIDs, userContext);
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> _return = null;
      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new MissingParameters("MissingParameters...");
    //throw new AccessDenied("AccessDenied...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1MarkupPortType#getMarkup(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp1.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp1.type.RuntimeContext  runtimeContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)org.exoplatform.services.wsrp1.type.MarkupParams  markupParams ,)org.exoplatform.services.wsrp1.type.MarkupContext  markupContext ,)org.exoplatform.services.wsrp1.type.SessionContext  sessionContext ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void getMarkup(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                        org.exoplatform.services.wsrp1.type.PortletContext portletContext,
                        org.exoplatform.services.wsrp1.type.RuntimeContext runtimeContext,
                        org.exoplatform.services.wsrp1.type.UserContext userContext,
                        org.exoplatform.services.wsrp1.type.MarkupParams markupParams,
                        javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.MarkupContext> markupContext,
                        javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.SessionContext> sessionContext,
                        javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws UnsupportedLocale,
                                                                                                                      InvalidRegistration,
                                                                                                                      InvalidUserCategory,
                                                                                                                      UnsupportedMimeType,
                                                                                                                      MissingParameters,
                                                                                                                      InvalidCookie,
                                                                                                                      AccessDenied,
                                                                                                                      InvalidHandle,
                                                                                                                      UnsupportedMode,
                                                                                                                      InvalidSession,
                                                                                                                      UnsupportedWindowState,
                                                                                                                      InconsistentParameters,
                                                                                                                      OperationFailed {
    LOG.info("Executing operation getMarkup");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(runtimeContext);
    System.out.println(userContext);
    System.out.println(markupParams);
    try {
      GetMarkup getMarkup = markupOperationsInterface.getMarkup(registrationContext, portletContext, runtimeContext, userContext, markupParams);
      org.exoplatform.services.wsrp1.type.MarkupContext markupContextValue = null;
      markupContext.value = markupContextValue;
      org.exoplatform.services.wsrp1.type.SessionContext sessionContextValue = null;
      sessionContext.value = sessionContextValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = null;
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new UnsupportedLocale("UnsupportedLocale...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new UnsupportedMimeType("UnsupportedMimeType...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InvalidCookie("InvalidCookie...");
    //throw new AccessDenied("AccessDenied...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new UnsupportedMode("UnsupportedMode...");
    //throw new InvalidSession("InvalidSession...");
    //throw new UnsupportedWindowState("UnsupportedWindowState...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1MarkupPortType#initCookie(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext )*
   */
  public java.util.List<org.exoplatform.services.wsrp1.type.Extension> initCookie(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext) throws InvalidRegistration,
                                                                                                                                                              AccessDenied,
                                                                                                                                                              OperationFailed {
    LOG.info("Executing operation initCookie");
    System.out.println(registrationContext);
    try {
      InitCookie initCookie = markupOperationsInterface.initCookie(registrationContext, userContext);
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> _return = null;
      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new AccessDenied("AccessDenied...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1MarkupPortType#performBlockingInteraction(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp1.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp1.type.RuntimeContext  runtimeContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)org.exoplatform.services.wsrp1.type.MarkupParams  markupParams ,)org.exoplatform.services.wsrp1.type.InteractionParams  interactionParams ,)org.exoplatform.services.wsrp1.type.UpdateResponse  updateResponse ,)java.lang.String  redirectURL ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void performBlockingInteraction(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                                         org.exoplatform.services.wsrp1.type.PortletContext portletContext,
                                         org.exoplatform.services.wsrp1.type.RuntimeContext runtimeContext,
                                         org.exoplatform.services.wsrp1.type.UserContext userContext,
                                         org.exoplatform.services.wsrp1.type.MarkupParams markupParams,
                                         org.exoplatform.services.wsrp1.type.InteractionParams interactionParams,
                                         javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.UpdateResponse> updateResponse,
                                         javax.xml.ws.Holder<java.lang.String> redirectURL,
                                         javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws UnsupportedLocale,
                                                                                                                                       InvalidRegistration,
                                                                                                                                       InvalidUserCategory,
                                                                                                                                       UnsupportedMimeType,
                                                                                                                                       MissingParameters,
                                                                                                                                       InvalidCookie,
                                                                                                                                       AccessDenied,
                                                                                                                                       InvalidHandle,
                                                                                                                                       UnsupportedMode,
                                                                                                                                       PortletStateChangeRequired,
                                                                                                                                       InvalidSession,
                                                                                                                                       UnsupportedWindowState,
                                                                                                                                       InconsistentParameters,
                                                                                                                                       OperationFailed {
    LOG.info("Executing operation performBlockingInteraction");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(runtimeContext);
    System.out.println(userContext);
    System.out.println(markupParams);
    System.out.println(interactionParams);
    try {
      BlockingInteractionResponse blockingInteractionResponse = markupOperationsInterface.performBlockingInteraction(registrationContext, portletContext, runtimeContext, userContext, markupParams, interactionParams);
      org.exoplatform.services.wsrp1.type.UpdateResponse updateResponseValue = null;
      updateResponse.value = updateResponseValue;
      java.lang.String redirectURLValue = "";
      redirectURL.value = redirectURLValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = null;
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new UnsupportedLocale("UnsupportedLocale...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new UnsupportedMimeType("UnsupportedMimeType...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InvalidCookie("InvalidCookie...");
    //throw new AccessDenied("AccessDenied...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new UnsupportedMode("UnsupportedMode...");
    //throw new PortletStateChangeRequired("PortletStateChangeRequired...");
    //throw new InvalidSession("InvalidSession...");
    //throw new UnsupportedWindowState("UnsupportedWindowState...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

}
