/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.exoplatform.services.wsrp1.bind;

import org.apache.commons.logging.Log;
import org.exoplatform.services.log.ExoLogger;
import org.exoplatform.services.ws.AbstractSingletonWebService;
import org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType;
import org.exoplatform.services.wsrp1.intf.AccessDenied;
import org.exoplatform.services.wsrp1.intf.ExportByValueNotSupported;
import org.exoplatform.services.wsrp1.intf.ExportNoLongerValid;
import org.exoplatform.services.wsrp1.intf.InconsistentParameters;
import org.exoplatform.services.wsrp1.intf.InvalidHandle;
import org.exoplatform.services.wsrp1.intf.InvalidRegistration;
import org.exoplatform.services.wsrp1.intf.InvalidUserCategory;
import org.exoplatform.services.wsrp1.intf.MissingParameters;
import org.exoplatform.services.wsrp1.intf.ModifyRegistrationRequired;
import org.exoplatform.services.wsrp1.intf.OperationFailed;
import org.exoplatform.services.wsrp1.intf.OperationNotSupported;
import org.exoplatform.services.wsrp1.intf.ResourceSuspended;
import org.exoplatform.services.wsrp1.producer.PortletManagementOperationsInterface;
import org.exoplatform.services.wsrp1.type.CopyPortletsResponse;
import org.exoplatform.services.wsrp1.type.DestroyPortletsResponse;
import org.exoplatform.services.wsrp1.type.ExportPortletsResponse;
import org.exoplatform.services.wsrp1.type.GetPortletsLifetimeResponse;
import org.exoplatform.services.wsrp1.type.ImportPortletsResponse;
import org.exoplatform.services.wsrp1.type.Lifetime;
import org.exoplatform.services.wsrp1.type.PortletContext;
import org.exoplatform.services.wsrp1.type.PortletDescriptionResponse;
import org.exoplatform.services.wsrp1.type.PortletPropertyDescriptionResponse;
import org.exoplatform.services.wsrp1.type.PropertyList;
import org.exoplatform.services.wsrp1.type.ReturnAny;
import org.exoplatform.services.wsrp1.type.SetPortletsLifetimeResponse;

/**
 * This class was generated by Apache CXF 2.1.2 Wed Oct 08 15:10:04 GMT+02:00
 * 2008 Generated source version: 2.1.2
 */

@javax.jws.WebService(name = "WSRPV1PortletManagementPortType", serviceName = "WSRPService", portName = "WSRP_v1_PortletManagement_Service", targetNamespace = "urn:oasis:names:tc:wsrp:v1:wsdl", wsdlLocation = "file:/home/alexey/java/eXoProjects/portlet-container/branches/2.1/component/plugins/wsrp1/wsdl/wsrp-service.wsdl", endpointInterface = "org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType")
public class WSRPV1PortletManagementPortTypeImpl implements WSRPV1PortletManagementPortType,
    AbstractSingletonWebService {

  private static final Log                     LOG = ExoLogger.getLogger(WSRPV1PortletManagementPortTypeImpl.class.getName());

  private PortletManagementOperationsInterface portletManagementOperationsInterface;

  public WSRPV1PortletManagementPortTypeImpl(PortletManagementOperationsInterface portletManagementOperationsInterface) {
    this.portletManagementOperationsInterface = portletManagementOperationsInterface;
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#clonePortlet(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp1.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)org.exoplatform.services.wsrp1.type.Lifetime  lifetime ,)java.lang.String  portletHandle ,)byte[]  portletState ,)org.exoplatform.services.wsrp1.type.Lifetime  scheduledDestruction ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void clonePortlet(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                           org.exoplatform.services.wsrp1.type.PortletContext portletContext,
                           org.exoplatform.services.wsrp1.type.UserContext userContext,
                           org.exoplatform.services.wsrp1.type.Lifetime lifetime,
                           javax.xml.ws.Holder<java.lang.String> portletHandle,
                           javax.xml.ws.Holder<byte[]> portletState,
                           javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.Lifetime> scheduledDestruction,
                           javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                         AccessDenied,
                                                                                                                         ResourceSuspended,
                                                                                                                         InvalidRegistration,
                                                                                                                         InvalidHandle,
                                                                                                                         InvalidUserCategory,
                                                                                                                         ModifyRegistrationRequired,
                                                                                                                         MissingParameters,
                                                                                                                         InconsistentParameters,
                                                                                                                         OperationFailed {
    LOG.info("Executing operation clonePortlet");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(userContext);
    System.out.println(lifetime);
    try {
      PortletContext response = portletManagementOperationsInterface.clonePortlet(registrationContext,
                                                                                  portletContext,
                                                                                  userContext,
                                                                                  lifetime);
      java.lang.String portletHandleValue = response.getPortletHandle();
      portletHandle.value = portletHandleValue;
      byte[] portletStateValue = response.getPortletState();
      portletState.value = portletStateValue;
      org.exoplatform.services.wsrp1.type.Lifetime scheduledDestructionValue = response.getScheduledDestruction();
      scheduledDestruction.value = scheduledDestructionValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#exportPortlets(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)java.util.List<org.exoplatform.services.wsrp1.type.PortletContext>  portletContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)org.exoplatform.services.wsrp1.type.Lifetime  lifetime ,)java.lang.Boolean  exportByValueRequired ,)byte[]  exportContext ,)java.util.List<org.exoplatform.services.wsrp1.type.ExportedPortlet>  exportedPortlet ,)java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets>  failedPortlets ,)org.exoplatform.services.wsrp1.type.ResourceList  resourceList ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void exportPortlets(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                             java.util.List<org.exoplatform.services.wsrp1.type.PortletContext> portletContext,
                             org.exoplatform.services.wsrp1.type.UserContext userContext,
                             javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.Lifetime> lifetime,
                             java.lang.Boolean exportByValueRequired,
                             javax.xml.ws.Holder<byte[]> exportContext,
                             javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.ExportedPortlet>> exportedPortlet,
                             javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets>> failedPortlets,
                             javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.ResourceList> resourceList,
                             javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                           ExportByValueNotSupported,
                                                                                                                           AccessDenied,
                                                                                                                           ResourceSuspended,
                                                                                                                           InvalidRegistration,
                                                                                                                           InvalidHandle,
                                                                                                                           InvalidUserCategory,
                                                                                                                           ModifyRegistrationRequired,
                                                                                                                           MissingParameters,
                                                                                                                           InconsistentParameters,
                                                                                                                           OperationFailed {
    LOG.info("Executing operation exportPortlets");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(userContext);
    System.out.println(lifetime.value);
    System.out.println(exportByValueRequired);
    try {
      ExportPortletsResponse response = portletManagementOperationsInterface.exportPortlets(registrationContext,
                                                                                            portletContext,
                                                                                            userContext,
                                                                                            lifetime.value,
                                                                                            exportByValueRequired);

      byte[] exportContextValue = response.getExportContext();
      exportContext.value = exportContextValue;
      java.util.List<org.exoplatform.services.wsrp1.type.ExportedPortlet> exportedPortletValue = response.getExportedPortlet();
      exportedPortlet.value = exportedPortletValue;
      java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets> failedPortletsValue = response.getFailedPortlets();
      failedPortlets.value = failedPortletsValue;
      org.exoplatform.services.wsrp1.type.ResourceList resourceListValue = response.getResourceList();
      resourceList.value = resourceListValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new ExportByValueNotSupported("ExportByValueNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#getPortletsLifetime(org.exoplatform.services.wsrp1.type.GetPortletsLifetime  getPortletsLifetime )*
   */
  public org.exoplatform.services.wsrp1.type.GetPortletsLifetimeResponse getPortletsLifetime(org.exoplatform.services.wsrp1.type.GetPortletsLifetime getPortletsLifetime) throws OperationNotSupported,
                                                                                                                                                                         AccessDenied,
                                                                                                                                                                         ResourceSuspended,
                                                                                                                                                                         InvalidRegistration,
                                                                                                                                                                         InvalidHandle,
                                                                                                                                                                         ModifyRegistrationRequired,
                                                                                                                                                                         InconsistentParameters,
                                                                                                                                                                         OperationFailed {
    LOG.info("Executing operation getPortletsLifetime");
    System.out.println(getPortletsLifetime);
    try {
      GetPortletsLifetimeResponse response = portletManagementOperationsInterface.getPortletsLifetime(getPortletsLifetime.getRegistrationContext(),
                                                                                                      getPortletsLifetime.getPortletContext(),
                                                                                                      getPortletsLifetime.getUserContext());
      org.exoplatform.services.wsrp1.type.GetPortletsLifetimeResponse _return = response;
      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#getPortletPropertyDescription(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp1.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)java.util.List<java.lang.String>  desiredLocales ,)org.exoplatform.services.wsrp1.type.ModelDescription  modelDescription ,)org.exoplatform.services.wsrp1.type.ResourceList  resourceList ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void getPortletPropertyDescription(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                                            org.exoplatform.services.wsrp1.type.PortletContext portletContext,
                                            org.exoplatform.services.wsrp1.type.UserContext userContext,
                                            java.util.List<java.lang.String> desiredLocales,
                                            javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.ModelDescription> modelDescription,
                                            javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.ResourceList> resourceList,
                                            javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                                          AccessDenied,
                                                                                                                                          ResourceSuspended,
                                                                                                                                          InvalidRegistration,
                                                                                                                                          InvalidHandle,
                                                                                                                                          InvalidUserCategory,
                                                                                                                                          ModifyRegistrationRequired,
                                                                                                                                          MissingParameters,
                                                                                                                                          InconsistentParameters,
                                                                                                                                          OperationFailed {
    LOG.info("Executing operation getPortletPropertyDescription");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(userContext);
    System.out.println(desiredLocales);
    try {
      PortletPropertyDescriptionResponse response = portletManagementOperationsInterface.getPortletPropertyDescription(registrationContext,
                                                                                                                       portletContext,
                                                                                                                       userContext,
                                                                                                                       desiredLocales);
      org.exoplatform.services.wsrp1.type.ModelDescription modelDescriptionValue = response.getModelDescription();
      modelDescription.value = modelDescriptionValue;
      org.exoplatform.services.wsrp1.type.ResourceList resourceListValue = response.getResourceList();
      resourceList.value = resourceListValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#getPortletDescription(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp1.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)java.util.List<java.lang.String>  desiredLocales ,)org.exoplatform.services.wsrp1.type.PortletDescription  portletDescription ,)org.exoplatform.services.wsrp1.type.ResourceList  resourceList ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void getPortletDescription(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                                    org.exoplatform.services.wsrp1.type.PortletContext portletContext,
                                    org.exoplatform.services.wsrp1.type.UserContext userContext,
                                    java.util.List<java.lang.String> desiredLocales,
                                    javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.PortletDescription> portletDescription,
                                    javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.ResourceList> resourceList,
                                    javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                                  AccessDenied,
                                                                                                                                  ResourceSuspended,
                                                                                                                                  InvalidRegistration,
                                                                                                                                  InvalidHandle,
                                                                                                                                  InvalidUserCategory,
                                                                                                                                  ModifyRegistrationRequired,
                                                                                                                                  MissingParameters,
                                                                                                                                  InconsistentParameters,
                                                                                                                                  OperationFailed {
    LOG.info("Executing operation getPortletDescription");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(userContext);
    System.out.println(desiredLocales);
    try {
      PortletDescriptionResponse response = portletManagementOperationsInterface.getPortletDescription(registrationContext,
                                                                                                       portletContext,
                                                                                                       userContext,
                                                                                                       desiredLocales);
      org.exoplatform.services.wsrp1.type.PortletDescription portletDescriptionValue = response.getPortletDescription();
      portletDescription.value = portletDescriptionValue;
      org.exoplatform.services.wsrp1.type.ResourceList resourceListValue = response.getResourceList();
      resourceList.value = resourceListValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#releaseExport(org.exoplatform.services.wsrp1.type.ReleaseExport  releaseExport )*
   */
  public org.exoplatform.services.wsrp1.type.ReturnAny releaseExport(org.exoplatform.services.wsrp1.type.ReleaseExport releaseExport) {
    LOG.info("Executing operation releaseExport");
    System.out.println(releaseExport);
    try {
      ReturnAny response = portletManagementOperationsInterface.releaseExport(releaseExport.getExportContext(),
                                                                              releaseExport.getUserContext(),
                                                                              releaseExport.getRegistrationContext());
      org.exoplatform.services.wsrp1.type.ReturnAny _return = response;
      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#copyPortlets(org.exoplatform.services.wsrp1.type.RegistrationContext  toRegistrationContext ,)org.exoplatform.services.wsrp1.type.UserContext  toUserContext ,)org.exoplatform.services.wsrp1.type.RegistrationContext  fromRegistrationContext ,)org.exoplatform.services.wsrp1.type.UserContext  fromUserContext ,)java.util.List<org.exoplatform.services.wsrp1.type.PortletContext>  fromPortletContexts ,)org.exoplatform.services.wsrp1.type.Lifetime  lifetime ,)java.util.List<org.exoplatform.services.wsrp1.type.CopiedPortlet>  copiedPortlets ,)java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets>  failedPortlets ,)org.exoplatform.services.wsrp1.type.ResourceList  resourceList ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void copyPortlets(org.exoplatform.services.wsrp1.type.RegistrationContext toRegistrationContext,
                           org.exoplatform.services.wsrp1.type.UserContext toUserContext,
                           org.exoplatform.services.wsrp1.type.RegistrationContext fromRegistrationContext,
                           org.exoplatform.services.wsrp1.type.UserContext fromUserContext,
                           java.util.List<org.exoplatform.services.wsrp1.type.PortletContext> fromPortletContexts,
                           org.exoplatform.services.wsrp1.type.Lifetime lifetime,
                           javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.CopiedPortlet>> copiedPortlets,
                           javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets>> failedPortlets,
                           javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.ResourceList> resourceList,
                           javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                         AccessDenied,
                                                                                                                         ResourceSuspended,
                                                                                                                         InvalidRegistration,
                                                                                                                         InvalidHandle,
                                                                                                                         InvalidUserCategory,
                                                                                                                         ModifyRegistrationRequired,
                                                                                                                         MissingParameters,
                                                                                                                         InconsistentParameters,
                                                                                                                         OperationFailed {
    LOG.info("Executing operation copyPortlets");
    System.out.println(toRegistrationContext);
    System.out.println(toUserContext);
    System.out.println(fromRegistrationContext);
    System.out.println(fromUserContext);
    System.out.println(fromPortletContexts);
    System.out.println(lifetime);
    try {
      CopyPortletsResponse response = portletManagementOperationsInterface.copyPortlets(toRegistrationContext,
                                                                                        toUserContext,
                                                                                        fromRegistrationContext,
                                                                                        fromUserContext,
                                                                                        fromPortletContexts,
                                                                                        lifetime);
      java.util.List<org.exoplatform.services.wsrp1.type.CopiedPortlet> copiedPortletsValue = response.getCopiedPortlets();
      copiedPortlets.value = copiedPortletsValue;
      java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets> failedPortletsValue = response.getFailedPortlets();
      failedPortlets.value = failedPortletsValue;
      org.exoplatform.services.wsrp1.type.ResourceList resourceListValue = response.getResourceList();
      resourceList.value = resourceListValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#setExportLifetime(org.exoplatform.services.wsrp1.type.SetExportLifetime  setExportLifetime )*
   */
  public org.exoplatform.services.wsrp1.type.Lifetime setExportLifetime(org.exoplatform.services.wsrp1.type.SetExportLifetime setExportLifetime) throws OperationNotSupported,
                                                                                                                                                AccessDenied,
                                                                                                                                                ResourceSuspended,
                                                                                                                                                InvalidRegistration,
                                                                                                                                                InvalidHandle,
                                                                                                                                                ModifyRegistrationRequired,
                                                                                                                                                OperationFailed {
    LOG.info("Executing operation setExportLifetime");
    System.out.println(setExportLifetime);
    try {
      Lifetime response = portletManagementOperationsInterface.setExportLifetime(setExportLifetime.getRegistrationContext(),
                                                                                 setExportLifetime.getExportContext(),
                                                                                 setExportLifetime.getUserContext(),
                                                                                 setExportLifetime.getLifetime());
      org.exoplatform.services.wsrp1.type.Lifetime _return = response;
      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#destroyPortlets(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)java.util.List<java.lang.String>  portletHandles ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets>  failedPortlets ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void destroyPortlets(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                              java.util.List<java.lang.String> portletHandles,
                              org.exoplatform.services.wsrp1.type.UserContext userContext,
                              javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets>> failedPortlets,
                              javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                            ResourceSuspended,
                                                                                                                            InvalidRegistration,
                                                                                                                            ModifyRegistrationRequired,
                                                                                                                            MissingParameters,
                                                                                                                            InconsistentParameters,
                                                                                                                            OperationFailed {
    LOG.info("Executing operation destroyPortlets");
    System.out.println(registrationContext);
    System.out.println(portletHandles);
    System.out.println(userContext);
    try {
      DestroyPortletsResponse response = portletManagementOperationsInterface.destroyPortlets(registrationContext,
                                                                                              portletHandles,
                                                                                              userContext);
      java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets> failedPortletsValue = response.getFailedPortlets();
      failedPortlets.value = failedPortletsValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#setPortletsLifetime(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)java.util.List<org.exoplatform.services.wsrp1.type.PortletContext>  portletContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)org.exoplatform.services.wsrp1.type.Lifetime  lifetime ,)java.util.List<org.exoplatform.services.wsrp1.type.PortletLifetime>  updatedPortlet ,)java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets>  failedPortlets ,)org.exoplatform.services.wsrp1.type.ResourceList  resourceList ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void setPortletsLifetime(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                                  java.util.List<org.exoplatform.services.wsrp1.type.PortletContext> portletContext,
                                  org.exoplatform.services.wsrp1.type.UserContext userContext,
                                  org.exoplatform.services.wsrp1.type.Lifetime lifetime,
                                  javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.PortletLifetime>> updatedPortlet,
                                  javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets>> failedPortlets,
                                  javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.ResourceList> resourceList,
                                  javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                                AccessDenied,
                                                                                                                                ResourceSuspended,
                                                                                                                                InvalidRegistration,
                                                                                                                                InvalidHandle,
                                                                                                                                ModifyRegistrationRequired,
                                                                                                                                InconsistentParameters,
                                                                                                                                OperationFailed {
    LOG.info("Executing operation setPortletsLifetime");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(userContext);
    System.out.println(lifetime);
    try {
      SetPortletsLifetimeResponse response = portletManagementOperationsInterface.setPortletsLifetime(registrationContext,
                                                                                                      portletContext,
                                                                                                      userContext,
                                                                                                      lifetime);
      java.util.List<org.exoplatform.services.wsrp1.type.PortletLifetime> updatedPortletValue = response.getUpdatedPortlet();
      updatedPortlet.value = updatedPortletValue;
      java.util.List<org.exoplatform.services.wsrp1.type.FailedPortlets> failedPortletsValue = response.getFailedPortlets();
      failedPortlets.value = failedPortletsValue;
      org.exoplatform.services.wsrp1.type.ResourceList resourceListValue = response.getResourceList();
      resourceList.value = resourceListValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#setPortletProperties(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp1.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)org.exoplatform.services.wsrp1.type.PropertyList  propertyList ,)java.lang.String  portletHandle ,)byte[]  portletState ,)org.exoplatform.services.wsrp1.type.Lifetime  scheduledDestruction ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void setPortletProperties(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                                   org.exoplatform.services.wsrp1.type.PortletContext portletContext,
                                   org.exoplatform.services.wsrp1.type.UserContext userContext,
                                   org.exoplatform.services.wsrp1.type.PropertyList propertyList,
                                   javax.xml.ws.Holder<java.lang.String> portletHandle,
                                   javax.xml.ws.Holder<byte[]> portletState,
                                   javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.Lifetime> scheduledDestruction,
                                   javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                                 AccessDenied,
                                                                                                                                 ResourceSuspended,
                                                                                                                                 InvalidRegistration,
                                                                                                                                 InvalidHandle,
                                                                                                                                 InvalidUserCategory,
                                                                                                                                 ModifyRegistrationRequired,
                                                                                                                                 MissingParameters,
                                                                                                                                 InconsistentParameters,
                                                                                                                                 OperationFailed {
    LOG.info("Executing operation setPortletProperties");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(userContext);
    System.out.println(propertyList);
    try {
      PortletContext response = portletManagementOperationsInterface.setPortletProperties(registrationContext,
                                                                                          portletContext,
                                                                                          userContext,
                                                                                          propertyList);
      java.lang.String portletHandleValue = response.getPortletHandle();
      portletHandle.value = portletHandleValue;
      byte[] portletStateValue = response.getPortletState();
      portletState.value = portletStateValue;
      org.exoplatform.services.wsrp1.type.Lifetime scheduledDestructionValue = response.getScheduledDestruction();
      scheduledDestruction.value = scheduledDestructionValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#getPortletProperties(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp1.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)java.util.List<java.lang.String>  names ,)java.util.List<org.exoplatform.services.wsrp1.type.Property>  properties ,)java.util.List<org.exoplatform.services.wsrp1.type.ResetProperty>  resetProperties ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void getPortletProperties(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                                   org.exoplatform.services.wsrp1.type.PortletContext portletContext,
                                   org.exoplatform.services.wsrp1.type.UserContext userContext,
                                   java.util.List<java.lang.String> names,
                                   javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Property>> properties,
                                   javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.ResetProperty>> resetProperties,
                                   javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                                 AccessDenied,
                                                                                                                                 ResourceSuspended,
                                                                                                                                 InvalidRegistration,
                                                                                                                                 InvalidHandle,
                                                                                                                                 InvalidUserCategory,
                                                                                                                                 ModifyRegistrationRequired,
                                                                                                                                 MissingParameters,
                                                                                                                                 InconsistentParameters,
                                                                                                                                 OperationFailed {
    LOG.info("Executing operation getPortletProperties");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(userContext);
    System.out.println(names);
    try {
      PropertyList response = portletManagementOperationsInterface.getPortletProperties(registrationContext,
                                                                                        portletContext,
                                                                                        userContext,
                                                                                        names);
      java.util.List<org.exoplatform.services.wsrp1.type.Property> propertiesValue = response.getProperties();
      properties.value = propertiesValue;
      java.util.List<org.exoplatform.services.wsrp1.type.ResetProperty> resetPropertiesValue = response.getResetProperties();
      resetProperties.value = resetPropertiesValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp1.intf.WSRPV1PortletManagementPortType#importPortlets(org.exoplatform.services.wsrp1.type.RegistrationContext  registrationContext ,)byte[]  importContext ,)java.util.List<org.exoplatform.services.wsrp1.type.ImportPortlet>  importPortlet ,)org.exoplatform.services.wsrp1.type.UserContext  userContext ,)org.exoplatform.services.wsrp1.type.Lifetime  lifetime ,)java.util.List<org.exoplatform.services.wsrp1.type.ImportedPortlet>  importedPortlets ,)java.util.List<org.exoplatform.services.wsrp1.type.ImportPortletsFailed>  importFailed ,)org.exoplatform.services.wsrp1.type.ResourceList  resourceList ,)java.util.List<org.exoplatform.services.wsrp1.type.Extension>  extensions )*
   */
  public void importPortlets(org.exoplatform.services.wsrp1.type.RegistrationContext registrationContext,
                             byte[] importContext,
                             java.util.List<org.exoplatform.services.wsrp1.type.ImportPortlet> importPortlet,
                             org.exoplatform.services.wsrp1.type.UserContext userContext,
                             org.exoplatform.services.wsrp1.type.Lifetime lifetime,
                             javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.ImportedPortlet>> importedPortlets,
                             javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.ImportPortletsFailed>> importFailed,
                             javax.xml.ws.Holder<org.exoplatform.services.wsrp1.type.ResourceList> resourceList,
                             javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp1.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                           ExportNoLongerValid,
                                                                                                                           AccessDenied,
                                                                                                                           ResourceSuspended,
                                                                                                                           InvalidRegistration,
                                                                                                                           InvalidUserCategory,
                                                                                                                           ModifyRegistrationRequired,
                                                                                                                           MissingParameters,
                                                                                                                           InconsistentParameters,
                                                                                                                           OperationFailed {
    LOG.info("Executing operation importPortlets");
    System.out.println(registrationContext);
    System.out.println(importContext);
    System.out.println(importPortlet);
    System.out.println(userContext);
    System.out.println(lifetime);
    try {
      ImportPortletsResponse response = portletManagementOperationsInterface.importPortlets(registrationContext,
                                                                                            importContext,
                                                                                            importPortlet,
                                                                                            userContext,
                                                                                            lifetime);
      java.util.List<org.exoplatform.services.wsrp1.type.ImportedPortlet> importedPortletsValue = response.getImportedPortlets();
      importedPortlets.value = importedPortletsValue;
      java.util.List<org.exoplatform.services.wsrp1.type.ImportPortletsFailed> importFailedValue = response.getImportFailed();
      importFailed.value = importFailedValue;
      org.exoplatform.services.wsrp1.type.ResourceList resourceListValue = response.getResourceList();
      resourceList.value = resourceListValue;
      java.util.List<org.exoplatform.services.wsrp1.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new ExportNoLongerValid("ExportNoLongerValid...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

}
