/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.exoplatform.services.wsrp2.bind.extensions;

import java.util.HashMap;

import org.apache.commons.logging.Log;
import org.exoplatform.services.log.ExoLogger;
import org.exoplatform.services.ws.AbstractSingletonWebService;

/**
 * This class was generated by Apache CXF 2.1.2 Wed Oct 08 15:10:04 GMT+02:00
 * 2008 Generated source version: 2.1.2
 */

@javax.jws.WebService(name = "WSRPV2ServiceAdministrationPortType", serviceName = "WSRPService", portName = "WSRP_v2_ServiceAdministration_Service"
//, targetNamespace = "urn:oasis:names:tc:wsrp:v2:wsdl", wsdlLocation = "file:/home/alexey/java/eXoProjects/portlet-container/branches/2.1/component/plugins/wsrp2/wsdl/wsrp-service.wsdl", endpointInterface = "org.exoplatform.services.wsrp2.bind.extensions.WSRPV2ServiceAdministrationPortType"
)
public class WSRPV2ServiceAdministrationPortTypeImpl implements
    WSRPV2ServiceAdministrationPortType, AbstractSingletonWebService {

  private static final Log               LOG = ExoLogger.getLogger(WSRPV2ServiceAdministrationPortTypeImpl.class.getName());

  private ServiceAdministrationInterface serviceAdministrationInterface;

  public WSRPV2ServiceAdministrationPortTypeImpl(ServiceAdministrationInterface serviceAdministrationInterface) {
    this.serviceAdministrationInterface = serviceAdministrationInterface;
    System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.WSRPV2ServiceAdministrationPortTypeImpl() ServiceAdministrationInterface = "
        + serviceAdministrationInterface);
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp2.intf.WSRPV2ServiceAdministrationPortType#getServiceAdministration(org.exoplatform.services.wsrp2.type.RegistrationContext  registrationContext ,)java.util.List<java.lang.String>  desiredLocales ,)java.util.List<java.lang.String>  portletHandles ,)org.exoplatform.services.wsrp2.type.UserContext  userContext ,)java.lang.Boolean  requiresRegistration ,)java.util.List<org.exoplatform.services.wsrp2.type.PortletDescription>  offeredPortlets ,)java.util.List<org.exoplatform.services.wsrp2.type.ItemDescription>  userCategoryDescriptions ,)java.util.List<org.exoplatform.services.wsrp2.type.ExtensionDescription>  extensionDescriptions ,)java.util.List<org.exoplatform.services.wsrp2.type.ItemDescription>  customWindowStateDescriptions ,)java.util.List<org.exoplatform.services.wsrp2.type.ItemDescription>  customModeDescriptions ,)org.exoplatform.services.wsrp2.type.CookieProtocol  requiresInitCookie ,)org.exoplatform.services.wsrp2.type.ModelDescription  registrationPropertyDescription ,)java.util.List<java.lang.String>  locales ,)org.exoplatform.services.wsrp2.type.ResourceList  resourceList ,)java.util.List<org.exoplatform.services.wsrp2.type.EventDescription>  eventDescriptions ,)org.exoplatform.services.wsrp2.type.ModelTypes  schemaType ,)java.util.List<java.lang.String>  supportedOptions ,)org.exoplatform.services.wsrp2.type.ExportDescription  exportDescription ,)java.lang.Boolean  mayReturnRegistrationState ,)java.util.List<org.exoplatform.services.wsrp2.type.Extension>  extensions )*
   */
  public void getServiceAdministration(javax.xml.ws.Holder<HashMap<String, String>> properties) {
    System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.getServiceAdministration() 1 = " + 1);

    LOG.info("Executing operation getServiceAdministration");
    System.out.println(properties);
    try {
      ServiceAdministration response = serviceAdministrationInterface.getServiceAdministration();//properties.value);
      
//      ServiceAdministration response = serviceAdministrationInterface.getServiceAdministration(properties);
      
      System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.getServiceAdministration() response = "
          + response);
      System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.getServiceAdministration() response.getProperties() = "
          + response.getProperties());
      System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.getServiceAdministration() response.getProperties().size() = "
          + response.getProperties().size());

      System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.getServiceAdministration() properties.value = "
          + properties.value);
      System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.getServiceAdministration() properties.value.size() = "
          + properties.value.size());

      properties.value = response.getProperties();
      System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.getServiceAdministration() properties.value = "
          + properties.value);
      System.out.println(">>> EXOMAN WSRPV2ServiceAdministrationPortTypeImpl.getServiceAdministration() properties.value.size() = "
          + properties.value.size());
      
//      return response.getProperties();
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new OperationFailed("OperationFailed...");
  }

}
