/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.exoplatform.services.wsrp2.bind;

import java.rmi.RemoteException;

import org.apache.commons.logging.Log;
import org.exoplatform.services.log.ExoLogger;
import org.exoplatform.services.ws.AbstractSingletonWebService;
import org.exoplatform.services.wsrp2.intf.AccessDenied;
import org.exoplatform.services.wsrp2.intf.InconsistentParameters;
import org.exoplatform.services.wsrp2.intf.InvalidCookie;
import org.exoplatform.services.wsrp2.intf.InvalidHandle;
import org.exoplatform.services.wsrp2.intf.InvalidRegistration;
import org.exoplatform.services.wsrp2.intf.InvalidSession;
import org.exoplatform.services.wsrp2.intf.InvalidUserCategory;
import org.exoplatform.services.wsrp2.intf.MissingParameters;
import org.exoplatform.services.wsrp2.intf.ModifyRegistrationRequired;
import org.exoplatform.services.wsrp2.intf.OperationFailed;
import org.exoplatform.services.wsrp2.intf.OperationNotSupported;
import org.exoplatform.services.wsrp2.intf.PortletStateChangeRequired;
import org.exoplatform.services.wsrp2.intf.ResourceSuspended;
import org.exoplatform.services.wsrp2.intf.UnsupportedLocale;
import org.exoplatform.services.wsrp2.intf.UnsupportedMimeType;
import org.exoplatform.services.wsrp2.intf.UnsupportedMode;
import org.exoplatform.services.wsrp2.intf.UnsupportedWindowState;
import org.exoplatform.services.wsrp2.intf.WSRPV2MarkupPortType;
import org.exoplatform.services.wsrp2.producer.MarkupOperationsInterface;
import org.exoplatform.services.wsrp2.type.BlockingInteractionResponse;
import org.exoplatform.services.wsrp2.type.HandleEventsResponse;
import org.exoplatform.services.wsrp2.type.MarkupResponse;
import org.exoplatform.services.wsrp2.type.ResourceResponse;
import org.exoplatform.services.wsrp2.type.ReturnAny;

/**
 * This class was generated by Apache CXF 2.1.2 Wed Oct 08 15:10:04 GMT+02:00
 * 2008 Generated source version: 2.1.2
 */

@javax.jws.WebService(name = "WSRPV2MarkupPortType", serviceName = "WSRPService", portName = "WSRP_v2_Markup_Service", targetNamespace = "urn:oasis:names:tc:wsrp:v2:wsdl", wsdlLocation = "file:/home/alexey/java/eXoProjects/portlet-container/branches/2.1/component/plugins/wsrp2/wsdl/wsrp-service.wsdl", endpointInterface = "org.exoplatform.services.wsrp2.intf.WSRPV2MarkupPortType")
public class WSRPV2MarkupPortTypeImpl implements WSRPV2MarkupPortType, AbstractSingletonWebService {

  private static final Log          LOG = ExoLogger.getLogger(WSRPV2MarkupPortTypeImpl.class.getName());

  private MarkupOperationsInterface markupOperationsInterface;

  public WSRPV2MarkupPortTypeImpl(MarkupOperationsInterface markupOperationsInterface) {
    this.markupOperationsInterface = markupOperationsInterface;
    System.out.println(">>> EXOMAN WSRPV2MarkupPortTypeImpl.WSRPV2MarkupPortTypeImpl() markupOperationsInterface = "
        + markupOperationsInterface);
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp2.intf.WSRPV2MarkupPortType#getResource(org.exoplatform.services.wsrp2.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp2.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp2.type.RuntimeContext  runtimeContext ,)org.exoplatform.services.wsrp2.type.UserContext  userContext ,)org.exoplatform.services.wsrp2.type.ResourceParams  resourceParams ,)org.exoplatform.services.wsrp2.type.ResourceContext  resourceContext ,)org.exoplatform.services.wsrp2.type.SessionContext  sessionContext ,)java.util.List<org.exoplatform.services.wsrp2.type.Extension>  extensions )*
   */
  public void getResource(org.exoplatform.services.wsrp2.type.RegistrationContext registrationContext,
                          javax.xml.ws.Holder<org.exoplatform.services.wsrp2.type.PortletContext> portletContext,
                          org.exoplatform.services.wsrp2.type.RuntimeContext runtimeContext,
                          org.exoplatform.services.wsrp2.type.UserContext userContext,
                          org.exoplatform.services.wsrp2.type.ResourceParams resourceParams,
                          javax.xml.ws.Holder<org.exoplatform.services.wsrp2.type.ResourceContext> resourceContext,
                          javax.xml.ws.Holder<org.exoplatform.services.wsrp2.type.SessionContext> sessionContext,
                          javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp2.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                        AccessDenied,
                                                                                                                        ResourceSuspended,
                                                                                                                        UnsupportedMimeType,
                                                                                                                        InvalidRegistration,
                                                                                                                        InvalidHandle,
                                                                                                                        InvalidCookie,
                                                                                                                        UnsupportedWindowState,
                                                                                                                        InvalidUserCategory,
                                                                                                                        UnsupportedMode,
                                                                                                                        ModifyRegistrationRequired,
                                                                                                                        InvalidSession,
                                                                                                                        MissingParameters,
                                                                                                                        InconsistentParameters,
                                                                                                                        OperationFailed,
                                                                                                                        UnsupportedLocale {
    LOG.info("Executing operation getResource");
    System.out.println(registrationContext);
    System.out.println(portletContext.value);
    System.out.println(runtimeContext);
    System.out.println(userContext);
    System.out.println(resourceParams);
    try {
      ResourceResponse response = markupOperationsInterface.getResource(registrationContext,
                                                                        portletContext.value,
                                                                        runtimeContext,
                                                                        userContext,
                                                                        resourceParams);
      org.exoplatform.services.wsrp2.type.ResourceContext resourceContextValue = response.getResourceContext();
      resourceContext.value = resourceContextValue;
      org.exoplatform.services.wsrp2.type.SessionContext sessionContextValue = response.getSessionContext();
      sessionContext.value = sessionContextValue;
      java.util.List<org.exoplatform.services.wsrp2.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new UnsupportedMimeType("UnsupportedMimeType...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidCookie("InvalidCookie...");
    //throw new UnsupportedWindowState("UnsupportedWindowState...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new UnsupportedMode("UnsupportedMode...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new InvalidSession("InvalidSession...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
    //throw new UnsupportedLocale("UnsupportedLocale...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp2.intf.WSRPV2MarkupPortType#initCookie(org.exoplatform.services.wsrp2.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp2.type.UserContext  userContext )*
   */
  public org.exoplatform.services.wsrp2.type.Extension initCookie(org.exoplatform.services.wsrp2.type.RegistrationContext registrationContext,
                                                                  org.exoplatform.services.wsrp2.type.UserContext userContext) throws OperationNotSupported,
                                                                                                                              AccessDenied,
                                                                                                                              ResourceSuspended,
                                                                                                                              InvalidRegistration,
                                                                                                                              ModifyRegistrationRequired,
                                                                                                                              OperationFailed {
    LOG.info("Executing operation initCookie");
    System.out.println(registrationContext);
    System.out.println(userContext);
    try {
      ReturnAny response = markupOperationsInterface.initCookie(registrationContext, userContext);
      org.exoplatform.services.wsrp2.type.Extension _return = response.getExtensions();
      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp2.intf.WSRPV2MarkupPortType#performBlockingInteraction(org.exoplatform.services.wsrp2.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp2.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp2.type.RuntimeContext  runtimeContext ,)org.exoplatform.services.wsrp2.type.UserContext  userContext ,)org.exoplatform.services.wsrp2.type.MarkupParams  markupParams ,)org.exoplatform.services.wsrp2.type.InteractionParams  interactionParams ,)org.exoplatform.services.wsrp2.type.UpdateResponse  updateResponse ,)java.lang.String  redirectURL ,)java.util.List<org.exoplatform.services.wsrp2.type.Extension>  extensions )*
   */
  public void performBlockingInteraction(org.exoplatform.services.wsrp2.type.RegistrationContext registrationContext,
                                         org.exoplatform.services.wsrp2.type.PortletContext portletContext,
                                         org.exoplatform.services.wsrp2.type.RuntimeContext runtimeContext,
                                         org.exoplatform.services.wsrp2.type.UserContext userContext,
                                         org.exoplatform.services.wsrp2.type.MarkupParams markupParams,
                                         org.exoplatform.services.wsrp2.type.InteractionParams interactionParams,
                                         javax.xml.ws.Holder<org.exoplatform.services.wsrp2.type.UpdateResponse> updateResponse,
                                         javax.xml.ws.Holder<java.lang.String> redirectURL,
                                         javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp2.type.Extension>> extensions) throws AccessDenied,
                                                                                                                                       ResourceSuspended,
                                                                                                                                       UnsupportedMimeType,
                                                                                                                                       InvalidRegistration,
                                                                                                                                       InvalidHandle,
                                                                                                                                       InvalidCookie,
                                                                                                                                       UnsupportedWindowState,
                                                                                                                                       InvalidUserCategory,
                                                                                                                                       UnsupportedMode,
                                                                                                                                       ModifyRegistrationRequired,
                                                                                                                                       InvalidSession,
                                                                                                                                       MissingParameters,
                                                                                                                                       InconsistentParameters,
                                                                                                                                       OperationFailed,
                                                                                                                                       UnsupportedLocale,
                                                                                                                                       PortletStateChangeRequired {
    LOG.info("Executing operation performBlockingInteraction");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(runtimeContext);
    System.out.println(userContext);
    System.out.println(markupParams);
    System.out.println(interactionParams);
    try {
      BlockingInteractionResponse response = markupOperationsInterface.performBlockingInteraction(registrationContext,
                                                                                                  portletContext,
                                                                                                  runtimeContext,
                                                                                                  userContext,
                                                                                                  markupParams,
                                                                                                  interactionParams);
      org.exoplatform.services.wsrp2.type.UpdateResponse updateResponseValue = response.getUpdateResponse();
      updateResponse.value = updateResponseValue;
      java.lang.String redirectURLValue = response.getRedirectURL();
      redirectURL.value = redirectURLValue;
      java.util.List<org.exoplatform.services.wsrp2.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new UnsupportedMimeType("UnsupportedMimeType...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidCookie("InvalidCookie...");
    //throw new UnsupportedWindowState("UnsupportedWindowState...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new UnsupportedMode("UnsupportedMode...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new InvalidSession("InvalidSession...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
    //throw new UnsupportedLocale("UnsupportedLocale...");
    //throw new PortletStateChangeRequired("PortletStateChangeRequired...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp2.intf.WSRPV2MarkupPortType#getMarkup(org.exoplatform.services.wsrp2.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp2.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp2.type.RuntimeContext  runtimeContext ,)org.exoplatform.services.wsrp2.type.UserContext  userContext ,)org.exoplatform.services.wsrp2.type.MarkupParams  markupParams ,)org.exoplatform.services.wsrp2.type.MarkupContext  markupContext ,)org.exoplatform.services.wsrp2.type.SessionContext  sessionContext ,)java.util.List<org.exoplatform.services.wsrp2.type.Extension>  extensions )*
   */
  public void getMarkup(org.exoplatform.services.wsrp2.type.RegistrationContext registrationContext,
                        org.exoplatform.services.wsrp2.type.PortletContext portletContext,
                        org.exoplatform.services.wsrp2.type.RuntimeContext runtimeContext,
                        org.exoplatform.services.wsrp2.type.UserContext userContext,
                        org.exoplatform.services.wsrp2.type.MarkupParams markupParams,
                        javax.xml.ws.Holder<org.exoplatform.services.wsrp2.type.MarkupContext> markupContext,
                        javax.xml.ws.Holder<org.exoplatform.services.wsrp2.type.SessionContext> sessionContext,
                        javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp2.type.Extension>> extensions) throws AccessDenied,
                                                                                                                      ResourceSuspended,
                                                                                                                      UnsupportedMimeType,
                                                                                                                      InvalidRegistration,
                                                                                                                      InvalidHandle,
                                                                                                                      InvalidCookie,
                                                                                                                      UnsupportedWindowState,
                                                                                                                      InvalidUserCategory,
                                                                                                                      UnsupportedMode,
                                                                                                                      ModifyRegistrationRequired,
                                                                                                                      InvalidSession,
                                                                                                                      MissingParameters,
                                                                                                                      InconsistentParameters,
                                                                                                                      OperationFailed,
                                                                                                                      UnsupportedLocale {
    LOG.info("Executing operation getMarkup");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(runtimeContext);
    System.out.println(userContext);
    System.out.println(markupParams);
    
    try {
      MarkupResponse response = markupOperationsInterface.getMarkup(registrationContext,
                                                                    portletContext,
                                                                    runtimeContext,
                                                                    userContext,
                                                                    markupParams);
      org.exoplatform.services.wsrp2.type.MarkupContext markupContextValue = response.getMarkupContext();
      markupContext.value = markupContextValue;
      org.exoplatform.services.wsrp2.type.SessionContext sessionContextValue = response.getSessionContext();
      sessionContext.value = sessionContextValue;
      java.util.List<org.exoplatform.services.wsrp2.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (RemoteException ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
      
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new UnsupportedMimeType("UnsupportedMimeType...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidCookie("InvalidCookie...");
    //throw new UnsupportedWindowState("UnsupportedWindowState...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new UnsupportedMode("UnsupportedMode...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new InvalidSession("InvalidSession...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
    //throw new UnsupportedLocale("UnsupportedLocale...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp2.intf.WSRPV2MarkupPortType#releaseSessions(org.exoplatform.services.wsrp2.type.RegistrationContext  registrationContext ,)java.util.List<java.lang.String>  sessionIDs ,)org.exoplatform.services.wsrp2.type.UserContext  userContext )*
   */
  public org.exoplatform.services.wsrp2.type.Extension releaseSessions(org.exoplatform.services.wsrp2.type.RegistrationContext registrationContext,
                                                                       java.util.List<java.lang.String> sessionIDs,
                                                                       org.exoplatform.services.wsrp2.type.UserContext userContext) throws OperationNotSupported,
                                                                                                                                   AccessDenied,
                                                                                                                                   ResourceSuspended,
                                                                                                                                   InvalidRegistration,
                                                                                                                                   ModifyRegistrationRequired,
                                                                                                                                   MissingParameters,
                                                                                                                                   OperationFailed {
    LOG.info("Executing operation releaseSessions");
    System.out.println(registrationContext);
    System.out.println(sessionIDs);
    System.out.println(userContext);
    try {
      ReturnAny response = markupOperationsInterface.releaseSessions(registrationContext,
                                                                     sessionIDs,
                                                                     userContext);
      org.exoplatform.services.wsrp2.type.Extension _return = response.getExtensions();
      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new MissingParameters("MissingParameters...");
    //throw new OperationFailed("OperationFailed...");
  }

  /* (non-Javadoc)
   * @see org.exoplatform.services.wsrp2.intf.WSRPV2MarkupPortType#handleEvents(org.exoplatform.services.wsrp2.type.RegistrationContext  registrationContext ,)org.exoplatform.services.wsrp2.type.PortletContext  portletContext ,)org.exoplatform.services.wsrp2.type.RuntimeContext  runtimeContext ,)org.exoplatform.services.wsrp2.type.UserContext  userContext ,)org.exoplatform.services.wsrp2.type.MarkupParams  markupParams ,)org.exoplatform.services.wsrp2.type.EventParams  eventParams ,)org.exoplatform.services.wsrp2.type.UpdateResponse  updateResponse ,)java.util.List<org.exoplatform.services.wsrp2.type.HandleEventsFailed>  failedEvents ,)java.util.List<org.exoplatform.services.wsrp2.type.Extension>  extensions )*
   */
  public void handleEvents(org.exoplatform.services.wsrp2.type.RegistrationContext registrationContext,
                           org.exoplatform.services.wsrp2.type.PortletContext portletContext,
                           org.exoplatform.services.wsrp2.type.RuntimeContext runtimeContext,
                           org.exoplatform.services.wsrp2.type.UserContext userContext,
                           org.exoplatform.services.wsrp2.type.MarkupParams markupParams,
                           org.exoplatform.services.wsrp2.type.EventParams eventParams,
                           javax.xml.ws.Holder<org.exoplatform.services.wsrp2.type.UpdateResponse> updateResponse,
                           javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp2.type.HandleEventsFailed>> failedEvents,
                           javax.xml.ws.Holder<java.util.List<org.exoplatform.services.wsrp2.type.Extension>> extensions) throws OperationNotSupported,
                                                                                                                         AccessDenied,
                                                                                                                         ResourceSuspended,
                                                                                                                         UnsupportedMimeType,
                                                                                                                         InvalidRegistration,
                                                                                                                         InvalidHandle,
                                                                                                                         InvalidCookie,
                                                                                                                         UnsupportedWindowState,
                                                                                                                         InvalidUserCategory,
                                                                                                                         UnsupportedMode,
                                                                                                                         ModifyRegistrationRequired,
                                                                                                                         InvalidSession,
                                                                                                                         MissingParameters,
                                                                                                                         InconsistentParameters,
                                                                                                                         OperationFailed,
                                                                                                                         UnsupportedLocale,
                                                                                                                         PortletStateChangeRequired {
    LOG.info("Executing operation handleEvents");
    System.out.println(registrationContext);
    System.out.println(portletContext);
    System.out.println(runtimeContext);
    System.out.println(userContext);
    System.out.println(markupParams);
    System.out.println(eventParams);
    try {
      HandleEventsResponse response = markupOperationsInterface.handleEvents(registrationContext,
                                                                             portletContext,
                                                                             runtimeContext,
                                                                             userContext,
                                                                             markupParams,
                                                                             eventParams);
      org.exoplatform.services.wsrp2.type.UpdateResponse updateResponseValue = response.getUpdateResponse();
      updateResponse.value = updateResponseValue;
      java.util.List<org.exoplatform.services.wsrp2.type.HandleEventsFailed> failedEventsValue = response.getFailedEvents();
      failedEvents.value = failedEventsValue;
      java.util.List<org.exoplatform.services.wsrp2.type.Extension> extensionsValue = response.getExtensions();
      extensions.value = extensionsValue;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
    //throw new OperationNotSupported("OperationNotSupported...");
    //throw new AccessDenied("AccessDenied...");
    //throw new ResourceSuspended("ResourceSuspended...");
    //throw new UnsupportedMimeType("UnsupportedMimeType...");
    //throw new InvalidRegistration("InvalidRegistration...");
    //throw new InvalidHandle("InvalidHandle...");
    //throw new InvalidCookie("InvalidCookie...");
    //throw new UnsupportedWindowState("UnsupportedWindowState...");
    //throw new InvalidUserCategory("InvalidUserCategory...");
    //throw new UnsupportedMode("UnsupportedMode...");
    //throw new ModifyRegistrationRequired("ModifyRegistrationRequired...");
    //throw new InvalidSession("InvalidSession...");
    //throw new MissingParameters("MissingParameters...");
    //throw new InconsistentParameters("InconsistentParameters...");
    //throw new OperationFailed("OperationFailed...");
    //throw new UnsupportedLocale("UnsupportedLocale...");
    //throw new PortletStateChangeRequired("PortletStateChangeRequired...");
  }

}
