#Thu Jul 24 16:42:41 EEST 2008
finder=cts
masterXMLFileOper=normal
harness.temp.directory=D\:\\exo\\projects\\projects\\portlet-container\\trunk\\applications\\tck-tests/portlettck2\\tmp
vendorPortalURL=http\://localhost\:8080/portal/tck/
portalURLFetcherMode=1
test_classname=com.sun.ts.tests.portlet.api.javax_portlet.PortletRequestDispatcher.SpecURLClient
porting.ts.url.class.1=com.sun.ts.lib.implementation.sun.common.SunRIURL
authConfigType=0
ts_home=D\:\\exo\\projects\\projects\\portlet-container\\trunk\\applications\\tck-tests/portlettck2
cts_home=D\:\\exo\\projects\\projects\\portlet-container\\trunk\\applications\\tck-tests/portlettck2
outputResponseContentLevel=1
harness.log.delayseconds=1
harness.log.port=2000
harness.log.traceflag=false
